name: nekotype_client
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1-alpha+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7
  lottie: ^3.1.2
  fluid_dialog: ^2.0.0
  animations: ^2.0.11
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  vibration: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lang/
